admini/urls.py
from django.conf.urls import url
from admini import views
from users import urls
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'admini'
urlpatterns = [
    url(r'^adminBase$', views.adminBase, name = 'adminBase'),

    url(r'^newMember$', views.newMember, name = 'newMember'),

    url(r'^newMeeting$', views.newMeeting, name = 'newMeeting'),

    url(r'^allMeeting$', views.allMeeting, name = 'allMeeting'),

    url(r'^allMember$', views.allMember, name = 'allMember'),

    url(r'^allPurchase$', views.allPurchase, name = 'allPurchase'),

    url(r'^newPurchase$', views.newPurchase, name = 'newPurchase'),

    url(r'^deleteMember/(?P<member_id>\d+)/$', views.deleteMember, name = 'deleteMember'),

    url(r'^editMember/(?P<member_id>\d+)/$', views.editMember, name = 'editMember'),


    ## Login and logout URL
    url(r'login/$', auth_views.LoginView.as_view(template_name='admini/login.html'),name="login"),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='admini/logout.html'),name="logout"),
    ]

database/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url(r'^', include('admini.urls')),
    # url(r'register', user_views.register, name = 'register'),
]

users/urls.py
from django.conf.urls import url
from users import views
from django.templatetags.static import static
# from database import settings
# from admini import views
app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    #
    url(r'more$', views.more, name = 'more'),
    #
    # url(r'some_view$', views.some_view, name = 'some_view'),

    url(r'formations$', views.formations, name = 'formations'),
    ]

users/models.py
from django.db import models

# Create your models here.

class Background(models.Model):
    photo = models.ImageField(default = "default.jpg", upload_to = 'background')

users/views.py
from django.shortcuts import render
from .models import Background
import io
from django.http import FileResponse
# from reportlab.pdfgen import canvas

from activities.models import Activitie

def base(request):
    return render(request, 'users/base.html')

def index(request):
    # images = Background.objects.all()
    activities = Activitie.objects.all()
    return render(request, 'users/index.html', {'activities' : activities})

def more(request):
    return render(request, 'users/more.html')

def formations(request):
    return render(request, 'users/formations.html')

users/templates/users/formations.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Hielo by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>About</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'base/assets/css/main.css' %}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{% url 'users:index' %}">NISAM</a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'users:index' %}">Accueil</a></li>
					<li><a href="{% url 'admini:login' %}">Admin</a></li>
					<li><a href="{% url 'users:more' %}">Plus</a></li>
				</ul>
			</nav>

		<!-- One -->
			<section id="One" class="wrapper style3">
				<div class="inner">
					<header class="align-center">
						<!-- <p>Eleifend vitae urna</p> -->
						<h2>A propos de NISAM</h2>
					</header>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper style2">
				<div class="inner">
					<div class="box">
						<div class="content">
							<header class="align-center">
								<!-- <p>maecenas sapien feugiat ex purus</p> -->
								<h2>Formations</h2>
							</header>

              <!-- <h4>Alternate</h4> -->
              <div class="table-wrapper">
                <table class="alt">
                  <thead>
                    <tr>
                      <th>Établissements</th>
                      <th>Formations</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>EST</td>
                      <td>
                        Génie Électrtique <br>
                        Génie Informatique <br>
                        Génie Mécanique <br>
                        Génie des Procédés <br>
                        Technique de Management
                      </td>
                    </tr>
                    <tr>
                      <td>ENSEM</td>
                      <td>Vis ac commodo adipiscing arcu aliquet.</td>
                    </tr>
                    <tr>
                      <td>FST</td>
                      <td> Morbi faucibus arcu accumsan lorem. <br></td>
                    </tr>
                    <tr>
                      <td>ENSA</td>
                      <td>Vitae integer tempus condimentum.</td>
                    </tr>
                    <tr>
                      <td>ENSAM</td>
                      <td>Ante turpis integer aliquet porttitor.</td>
                    </tr>
                  </tbody>
                  <!-- <tfoot>
                    <tr>
                      <td colspan="2"></td>
                      <td>100.00</td>
                    </tr>
                  </tfoot> -->
                </table>
              </div>

						</div>
					</div>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="https://web.facebook.com/nisamrabat/" class="icon fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/nisam_rabat/" class="icon fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
						<li><a href="mailto:mainbrain02@gmail.com" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
					</ul>
				</div>
				<div class="copyright">
					&copy; Baba Prince. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'base/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'base/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'base/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'base/assets/js/util.js' %}"></script>
			<script src="{% static 'base/assets/js/main.js' %}"></script>

	</body>
</html>

users/templates/users/index.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Hielo by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Nisam</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'base/assets/css/main.css' %}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header" class="alt">
				<div class="logo"><a href="{% url 'users:index' %}">NISAM</a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'users:index' %}">Accueil</a></li>
					<li><a href="{% url 'admini:login' %}">Admin</a></li>
					<li><a href="{% url 'users:formations' %}">Formations</a></li>
					<li><a href="{% url 'users:more' %}">A notre sujet</a></li>
				</ul>
			</nav>

		<!-- Banner -->
			<section class="banner full">
				<article>
					<img src="{% static 'base/img/images/01.jpg' %}" alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</a></p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/02.jpg' %}" alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/03.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/04.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/05.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/06.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/07.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/14.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/19.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/24.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
				<article>
					<img src="{% static 'base/img/images/25.jpg' %}"  alt="" />
					<div class="inner">
						<header>
							<p>Nigerian Students Association in Morocco</p>
							<h2>NISAM</h2>
						</header>
					</div>
				</article>
			</section>

		<!-- One -->
			<section id="one" class="wrapper style2">
				<div class="inner">
					<div class="grid-style">

						<!-- <div>
							<div class="box">
								<div class="image fit">
									<img src="{% static 'base/img/images/pic02.jpg' %}" alt="" />
								</div>
								<div class="content">
									<header class="align-center">
										<p>Rencontre extraordinaire de NISAM</p>
										<h2>Les activités a venir seront ici</h2>
									</header>
									<p> Cras aliquet urna ut sapien tincidunt, quis malesuada elit facilisis. Vestibulum sit amet tortor velit. Nam elementum nibh a libero pharetra elementum. Maecenas feugiat ex purus, quis volutpat lacus placerat malesuada.</p>
									<footer class="align-center">
										<a href="{% url 'users:more' %}" class="button alt">Learn More</a>
									</footer>
								</div>
							</div>
						</div> -->

						<!-- <div>
							<div class="box">
								<div class="image fit">
									<img src="{% static 'base/img/images/pic02.jpg' %}" alt="" />
								</div>
								<div class="content">
									<header class="align-center">
										<p>Rencontre extraordinaire de NISAM</p>
										<h2>Les activités a venir seront ici</h2>
									</header>
									<p> Cras aliquet urna ut sapien tincidunt, quis malesuada elit facilisis. Vestibulum sit amet tortor velit. Nam elementum nibh a libero pharetra elementum. Maecenas feugiat ex purus, quis volutpat lacus placerat malesuada.</p>
									<footer class="align-center">
										<a href="{% url 'users:more' %}" class="button alt">Learn More</a>
									</footer>
								</div>
							</div>
						</div> -->

						<!-- <div>
							<div class="box">
								<div class="image fit">
									<img src="{% static 'base/img/images/pic02.jpg' %}" alt="" />
								</div>
								<div class="content">
									<header class="align-center">
										<p>Rencontre extraordinaire de NISAM</p>
										<h2>Les activités a venir seront ici</h2>
									</header>
									<p> Cras aliquet urna ut sapien tincidunt, quis malesuada elit facilisis. Vestibulum sit amet tortor velit. Nam elementum nibh a libero pharetra elementum. Maecenas feugiat ex purus, quis volutpat lacus placerat malesuada.</p>
									<footer class="align-center">
										<a href="{% url 'users:more' %}" class="button alt">Learn More</a>
									</footer>
								</div>
							</div>
						</div> -->

						{% for activity in activities %}
						<div>
							<div class="box">
								<div class="image fit">
									<img src="/{{ BASIC_DIR }}/{{activity.image}" alt="" />
								</div>
								<div class="content">
									<header class="align-center">
										<p>mattis elementum sapien pretium tellus</p>
										<h2>{{activity.title}}</h2>
									</header>
									<p> {{activity.body}}</p>
									<footer class="align-center">
										<a href="{% url 'users:more' %}" class="button alt">Learn More</a>
									</footer>
								</div>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</section>

		<!-- Two -->
				<div class="inner">
					<header class="align-center">
						<p>Nam vel ante sit amet libero scelerisque facilisis eleifend vitae urna</p>
						<h2>Morbi maximus justo</h2>
					</header>
				</div>
			</section> -->

		<!-- Three -->
			<section id="three" class="wrapper style2">
				<div class="inner">
					<header class="align-center">
						<h2>Quelques images des membres de l'association</h2>
					</header>
					<div class="gallery">
						<div>
							<div class="image fit">
								<a href="#"><img src="{% static 'base/img/images/01.jpg' %}" alt="" /></a>
							</div>
						</div>
						<div>
							<div class="image fit">
								<a href="#"><img src="{% static 'base/img/images/02.jpg' %}" alt="" /></a>
							</div>
						</div>
						<div>
							<div class="image fit">
								<a href="#"><img src="{% static 'base/img/images/03.jpg' %}" alt="" /></a>
							</div>
						</div>
						<div>
							<div class="image fit">
								<a href="#"><img src="{% static 'base/img/images/04.jpg' %}" alt="" /></a>
							</div>
						</div>
					</div>
				</div>
			</section>


		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="https://web.facebook.com/nisamrabat/" class="icon fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/nisam_rabat/" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="mailto:hambertvalentine@gmail .com" class="icon fa-envelope-o" target="_blank"><span class="label">Email</span></a></li>
					</ul>
				</div>
				<div class="copyright">
					&copy; Baba Prince. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'base/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'base/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'base/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'base/assets/js/util.js' %}"></script>
			<script src="{% static 'base/assets/js/main.js' %}"></script>

	</body>
</html>

users/templates/users/more.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Hielo by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>About</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'base/assets/css/main.css' %}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{% url 'users:index' %}">NISAM</a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'users:index' %}">Accueil</a></li>
					<li><a href="{% url 'admini:login' %}">Admin</a></li>
					<li><a href="{% url 'users:more' %}">Plus</a></li>
				</ul>
			</nav>

		<!-- One -->
			<section id="One" class="wrapper style3">
				<div class="inner">
					<header class="align-center">
						<h2>A propos de NISAM	</h2>
					</header>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper style2">
				<div class="inner">
					<div class="box">
						<div class="content">
							<header class="align-center">
								<h2>A notre sujet</h2>
							</header>
							<p>L'Association des étudiants nigérians au Maroc (NISAM) a été créée le 19
								Février 2004 en raison des difficultés rencontrées par les étudiants nigérians au quotidien au Maroc
								qui invite et appelle à l'unité et à un esprit de solidarité, de compréhension et d'amitié à l'intérieur
								la communauté des étudiants nigérians, l'ambassade du Nigéria au Maroc et d'autres
								agences à l'intérieur et à l'extérieur du Maroc.
							</p>

							<p>La nécessité d'établir et de promouvoir une relation durable pour tous les futurs étudiants et
								ceux déjà au Maroc pour assurer et encourager une bonne éthique de travail pour tous les étudiants
								impliqués afin de contribuer positivement au développement de notre pays d'origine, le Nigéria.
							</p>

							<p>Cependant, en raison du nouveau développement et des changements au sein des étudiants nigérians en
								ces dernières années, les cadres de la session académique 2020/2021 jugent donc nécessaire de
								modifier la constitution.
							</p>
						</div>
					</div>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="https://web.facebook.com/nisamrabat/" class="icon fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/nisam_rabat/" class="icon fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
						<li><a href="mailto:mainbrain02@gmail.com" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
					</ul>
				</div>
				<div class="copyright">
					&copy; Baba Prince. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'base/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'base/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'base/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'base/assets/js/util.js' %}"></script>
			<script src="{% static 'base/assets/js/main.js' %}"></script>

	</body>
</html>