admini/urls.py
from django.conf.urls import url
from admini import views
from users import urls
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'admini'
urlpatterns = [
    url(r'^adminBase$', views.adminBase, name = 'adminBase'),

    url(r'^newMember$', views.newMember, name = 'newMember'),

    url(r'^newMeeting$', views.newMeeting, name = 'newMeeting'),

    url(r'^allMeeting$', views.allMeeting, name = 'allMeeting'),

    url(r'^allMember$', views.allMember, name = 'allMember'),

    url(r'^allPurchase$', views.allPurchase, name = 'allPurchase'),

    url(r'^newPurchase$', views.newPurchase, name = 'newPurchase'),

    url(r'^deleteMember/(?P<member_id>\d+)/$', views.deleteMember, name = 'deleteMember'),

    url(r'^editMember/(?P<member_id>\d+)/$', views.editMember, name = 'editMember'),


    ## Login and logout URL
    url(r'login/$', auth_views.LoginView.as_view(template_name='admini/login.html'),name="login"),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='admini/logout.html'),name="logout"),
    ]

database/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url(r'^', include('admini.urls')),
    # url(r'register', user_views.register, name = 'register'),
]

users/urls.py
from django.conf.urls import url
from users import views
from django.templatetags.static import static
# from database import settings
# from admini import views
app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    #
    url(r'more$', views.more, name = 'more'),
    #
    # url(r'some_view$', views.some_view, name = 'some_view'),

    url(r'formations$', views.formations, name = 'formations'),
    ]

admini/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from phone_field import PhoneField
from PIL import Image
from django_countries.fields import CountryField

# Create your models here.


class Member(models.Model):
    amci = models.CharField(max_length = 8, unique = True, default = "")
    nom = models.CharField(max_length = 50, default="")
    prenoms = models.CharField(max_length = 50, default="")
    mail = models.EmailField(max_length = 100, default="")
    date_nais = models.DateField()
    tel = PhoneNumberField(blank=True)
    annee_bourse = models.IntegerField(default = 2020)
    instagram = models.CharField(max_length = 250, default = "", blank = True)
    facebook = models.CharField(max_length = 250, default = "", blank = True)
    twitter = models.CharField(max_length = 250, default = "", blank = True)

    def __str__(self):
        return "%s" %(self.nom)



class Reunion(models.Model):
    nom = models.CharField(max_length = 60)
    pdf = models.FileField(upload_to = 'pdf')
    
    def __str__(self):
        return "%s" %(self.nom)



class Treasury(models.Model):
    nom = models.CharField(max_length = 60)
    prix = models.DecimalField(9999, max_digits = 6, decimal_places = 2)
    date = models.DateField()
    def __str__(self):
        return "%s" %(self.nom)


class BoardMembers(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    status_choices = (
        ('Super Admin', 'Super Admin'),
        ('Treasurer', 'Treasurer'),
        ('Secretary', 'Secretary'),
    )
    statut = models.CharField(max_length = 15, choices = status_choices, default = "Super Admin")
    nom = models.CharField(max_length = 50, default="")
    prenoms = models.CharField(max_length = 50, default="")
    mail = models.EmailField(max_length = 100, default="")
    date_nais = models.DateField()
    tel = PhoneNumberField(blank=True)
    def __str__(self):
        return "%s %s" %(self.nom, self.prenoms)

admini/forms.py
from django import forms
from admini.models import Member
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
from django_countries.fields import CountryField


### Class django pour afficher le calendrier au niveau du formulaire
class dateInput(forms.DateInput):
####Le formulaire pour l'inscription du candidat####
    input_type = 'date'
class memberForm(forms.Form):
    amci = forms.CharField(max_length = 8, label = "AMCI")
    fname = forms.CharField(max_length = 50, label = "Nom")
    lname = forms.CharField(max_length = 50, label = "Prénom")
    mail = forms.EmailField(max_length = 60, label = "Adresse mail")
    date_nais = forms.DateField(label = "Date de naissance", widget = dateInput)
    tel = PhoneNumberField(max_length = 15, label = "Téléphone")
    annee_bourse = forms.IntegerField(label = "Année d'attribution de la bourse")
    instagram = forms.CharField(max_length = 60, label = "Instagram", required = False)
    facebook = forms.CharField(max_length = 60, label = "Facebook", required = False)
    twitter = forms.CharField(max_length = 60, label = "Twitter", required = False)


class treasuryForm(forms.Form):
    nom = forms.CharField(max_length = 60, label = "Nom du produit")
    prix = forms.DecimalField(label = "Prix")
    date = forms.DateField(widget = dateInput, label = "Date d'achat")


class meetingForm(forms.Form):
    nom = forms.CharField(max_length = 60, label = "Objet de la reunion")
    pdf = forms.FileField(label = "Compte rendu de la reunion")

admini/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from admini.models import Member, Treasury, Reunion
from admini.forms import memberForm, treasuryForm, meetingForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
@login_required
def adminBase(request):
    return render(request, 'admini/adminBase.html')



def login(request):
    return render(request, 'admini/login.html')


@login_required
def newMember(request):
    submitted = False
    if request.method == 'POST':
        form = memberForm(request.POST, request.FILES)
        if form.is_valid():
            amci = request.POST['amci']
            fname = request.POST['fname']
            lname = request.POST['lname']
            mail = request.POST['mail']
            date_nais = request.POST['date_nais']
            tel = request.POST['tel']
            annee_bourse = request.POST['annee_bourse']
            instagram = request.POST['instagram']
            facebook = request.POST['facebook']
            twitter = request.POST['twitter']
            member = Member(amci = amci, nom = fname, prenoms = lname, mail = mail, date_nais = date_nais, tel = tel, annee_bourse = annee_bourse, instagram = instagram, facebook = facebook, twitter = twitter)
            member.save()
            return redirect('admini:allMember')
    else:
        form = memberForm()
    return render(request, 'admini/newMember.html', {'form': form})



@login_required
def newPurchase(request):
    submitted = False
    if request.method == 'POST':
        form = treasuryForm(request.POST, request.FILES)
        if form.is_valid():
            nom = request.POST['nom']
            prix = request.POST['prix']
            date = request.POST['date']
            purchase = Treasury(nom = nom, prix = prix, date = date)
            purchase.save()
            return redirect('admini:allPurchase')
    else:
        form = treasuryForm()
    return render(request, 'admini/newPurchase.html', {'form': form})

@login_required
def allMember(request):
    members = Member.objects.all()
    paginator = Paginator(members, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'admini/allMember.html', {'page_obj': page_obj})


@login_required
def allPurchase(request):
    purchase = Treasury.objects.all()
    paginator = Paginator(purchase, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'admini/allPurchase.html', {'page_obj': page_obj})


@login_required
def deleteMember(request, member_id):
    member = Member.objects.get(id = member_id)
    member.delete()
    return redirect('admini:allMember')



@login_required
def editMember(request, member_id):
    if request.method == 'POST':
        instagram = request.POST['instagram']
        facebook = request.POST['facebook']
        twitter = request.POST['twitter']
        record = Member.objects.get(id = member_id)
        record.instagram = instagram
        record.facebook = facebook
        record.twitter = twitter
        record.save()
        return redirect('admini:allMember')

    else:
        members = Member.objects.get(id = member_id)
        return render(request, 'admini/editMember.html', {'members': members})




@login_required
def newMeeting(request):
    submitted = False
    if request.method == 'POST':
        form = meetingForm(request.POST, request.FILES)
        if form.is_valid():
            nom = request.POST['nom']
            pdf = request.FILES['pdf']
            meeting = Reunion(nom = nom, pdf = pdf)
            meeting.save()
            return redirect('admini:allMeeting')
    else:
        form = meetingForm()
    return render(request, 'admini/newMeeting.html', {'form': form})



@login_required
def allMeeting(request):
    meeting = Reunion.objects.all()
    paginator = Paginator(meeting, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'admini/allMeeting.html', {'page_obj': page_obj})

admini/templates/admini/allMeeting.html
{% extends "admini/adminBase.html" %}

{% block new %}
<section class="content">

  <div class="box">
    <div class="box-header">
      <h3 class="box-title">La liste des Reunions</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
      <table class="table table-bordered">
        <tr>
          <th style="width: 10px">#</th>
          <th>NOM</th>
          <th>PDF</th>
        </tr>
        {% for meeting in page_obj %}
        <tr>
          <td> <b>{{ forloop.counter }}</b> </td>
          <td> <b>{{ meeting.nom }}</b> </td>
          <td> <b>{{ meeting.pdf }}</b> </td>

        </tr>
        {% endfor %}
      </table>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; <b>Premier</b> &ensp;</a>
        <a href="?page={{ page_obj.previous_page_number }}"> <b>Précédent</b> &ensp;</a>
    {% endif %}

    <span class="current">
        Page <b>{{ page_obj.number }}</b> sur {{ page_obj.paginator.num_pages }} &ensp;
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"> <b>Suivant</b> &ensp;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}"> <b>Dernier</b> &raquo;</a>
    {% endif %}
  </span>
</div>

    </div><!-- /.box-body -->
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/allMember.html
{% extends "admini/adminBase.html" %}

{% block new %}
<section class="content">

  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Les Membres de l'Association</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
      <table class="table table-bordered">
        <tr>
          <th style="width: 10px">#</th>
          <th>AMCI</th>
          <th>NOMS</th>
          <th>MAIL</th>
          <th style="width: 40px">TEL</th>
        </tr>
        {% for member in page_obj %}
        <tr>
          <td> <b>{{ forloop.counter }}</b> </td>
          <td> <b style = "color:#DC143C">{{ member.amci }}</b> </td>
          <td> <b>{{ member.nom }} {{ member.prenoms }}</b> </td>
          <td> <b>{{ member.mail }}</b> </td>
          <td> <b>{{ member.tel }}</b> </td>
          {% if user.boardmembers.statut == "Super Admin" %}
          <td> <a href="{% url 'admini:editMember' member_id=member.id %}">Éditer</a> </td>
          <td> <a href="{% url 'admini:deleteMember' member_id=member.id %}">Supprimer</a> </td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; <b>Premier</b> &ensp;</a>
        <a href="?page={{ page_obj.previous_page_number }}"> <b>Précédent</b> &ensp;</a>
    {% endif %}

    <span class="current">
        Page <b>{{ page_obj.number }}</b> sur {{ page_obj.paginator.num_pages }} &ensp;
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"> <b>Suivant</b> &ensp;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}"> <b>Dernier</b> &raquo;</a>
    {% endif %}
  </span>
</div>

    </div><!-- /.box-body -->
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/allPurchase.html
{% extends "admini/adminBase.html" %}

{% block new %}
<section class="content">

  <div class="box">
    <div class="box-header">
      <h3 class="box-title">La liste des achats</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
      <table class="table table-bordered">
        <tr>
          <th style="width: 10px">#</th>
          <th>NOM</th>
          <th>PRIX</th>
          <th>DATE D'ACHAT</th>
        </tr>
        {% for purchase in page_obj %}
        <tr>
          <td> <b>{{ forloop.counter }}</b> </td>
          <td> <b>{{ purchase.nom }}</b> </td>
          <td> <b style = "color:#DC143C">{{ purchase.prix }} DH</b> </td>
          <td> <b>{{ purchase.date }}</b> </td>

        </tr>
        {% endfor %}
      </table>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; <b>Premier</b> &ensp;</a>
        <a href="?page={{ page_obj.previous_page_number }}"> <b>Précédent</b> &ensp;</a>
    {% endif %}

    <span class="current">
        Page <b>{{ page_obj.number }}</b> sur {{ page_obj.paginator.num_pages }} &ensp;
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"> <b>Suivant</b> &ensp;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}"> <b>Dernier</b> &raquo;</a>
    {% endif %}
  </span>
</div>

    </div><!-- /.box-body -->
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/editMember.html
{% extends "admini/adminBase.html" %}
{% load crispy_forms_tags %}
{% block new %}
<section class="content">

  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Nouveau Membre</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="box-body">
        <!-- <div class="form-group">
          <label>AMCI</label>
          <input type="text" class="form-control" name="amci" value="{{members.amci}}">
        </div>
        <div class="form-group">
          <label>Nom</label>
          <input type="text" class="form-control" name="fname" value="{{members.nom}}">
        </div>
        <div class="form-group">
          <label>Prénom</label>
          <input type="text" class="form-control" name="lname" value="{{members.prenoms}}">
        </div>
        <div class="form-group">
          <label>Adresse mail</label>
          <input type="email" class="form-control" name="mail" value="{{members.mail}}">
        </div>
        <div class="form-group">
          <label>Téléphone</label>
          <input type="text" class="form-control" name="tel" value="{{members.tel}}">
        </div>
        <div class="form-group">
          <label>Année d'obtention de la bourse</label>
          <input type="text" class="form-control" name="annee_bourse" value="{{members.annee_bourse}}">
        </div> -->
        <div class="form-group">
          <label>Instagram</label>
          <input type="text" class="form-control" name="instagram" value="{{members.instagram}}">
        </div>
        <div class="form-group">
          <label>Facebook</label>
          <input type="text" class="form-control" name="facebook" value="{{members.facebook}}">
        </div>
        <div class="form-group">
          <label>Twitter</label>
          <input type="text" class="form-control" name="twitter" value="{{members.twitter}}">
        </div>
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </div>
    </form>
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/login.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
		============================================ -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="{% static 'login/img/favicon.ico' %}"> -->
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/bootstrap.min.css' %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'login/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'login/css/owl.transitions.css' %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/animate.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/normalize.css' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/main.css' %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/morrisjs/morris.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/metisMenu/metisMenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'login/css/metisMenu/metisMenu-vertical.css' %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/calendar/fullcalendar.min.css' %}">
    <link rel="stylesheet" href="{% static 'login/css/calendar/fullcalendar.print.min.css' %}">
    <!-- forms CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/form/all-type-forms.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'login/css/responsive.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'login/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="error-pagewrap">
		<div class="error-page-int">
			<div class="text-center m-b-md custom-login">
				<p></p>
			</div>
			<div class="content-error">
				<div class="hpanel">
                    <div class="panel-body">
                      <div class="">
                        <h1 align = center <b>Connexion</b> </h1>
                      </div>
                        <form action="" method="post">
                          {% csrf_token %}
                            <div class="form-group">
                                {{ form|crispy }}
                            </div>
                            <input type="submit" name="" value="Login" class="btn btn-success btn-block loginbtn">
                            <a href="{% url 'users:index' %}" class="btn btn-success btn-block">Home</a>
                        </form>
                    </div>
                </div>
			</div>
			<!-- <div class="text-center login-footer">
				<p>Copyright © 2020. All rights reserved<a href="https://colorlib.com/wp/templates/"></a></p>
			</div> -->
		</div>
    </div>
    <!-- jquery
		============================================ -->
    <script src="{% static 'login/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'login/js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'login/js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'login/js/jquery-price-slider.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'login/js/jquery.meanmenu.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'login/js/owl.carousel.min.js' %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static 'login/js/jquery.sticky.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'login/js/jquery.scrollUp.min.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'login/js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'login/js/scrollbar/mCustomScrollbar-active.js' %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static 'login/js/metisMenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'login/js/metisMenu/metisMenu-active.js' %}"></script>
    <!-- tab JS
		============================================ -->
    <script src="{% static 'login/js/tab.js' %}"></script>
    <!-- icheck JS
		============================================ -->
    <script src="{% static 'login/js/icheck/icheck.min.js' %}"></script>
    <script src="{% static 'login/js/icheck/icheck-active.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'login/js/plugins.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'login/js/main.js' %}"></script>
    <!-- tawk chat JS
		============================================ -->
    <!-- <script src="{% static 'login/js/tawk-chat.js' %}"></script> -->
</body>

</html>

admini/templates/admini/login0.html
{% extends "admini/loginBase.html" %}
{% load crispy_forms_tags %}
{% block new %}
        <div class="box-header">
          <h3 class="box-title">Connexion</h3>
        </div><!-- /.box-header -->
        <form role="form" class="" action="" method="POST">
          {% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              {{ form|crispy }}
            </div>
          </div>
          <div class="box-footer">
            <input type="submit" class="btn btn-primary" name="" value="Valider">
          </div>
        </form>
{% endblock new %}

admini/templates/admini/logout.html
{% block new %}
    <div class="sectiontitle">
      <h6 class="heading">Déconexion</h6>
    </div>
    <div class="group">
      <div class="one_half first">
          <h2>Vous avez été déconnecté</h2>
          <div class="border-top-pt-3">
            <small class="text-muted">
             <a class="ml-2" href="{% url 'admini:login' %}">Se connecter encore</a>
            </small>
          </div>
      </div>
    </div>
{% endblock new %}

admini/templates/admini/newMeeting.html
{% extends "admini/adminBase.html" %}
{% load crispy_forms_tags %}
{% block new %}
<section class="content">

  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Nouvelle Reunion</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="box-body">
        {{ form|crispy }}
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </div>
    </form>
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/newMember.html
{% extends "admini/adminBase.html" %}
{% load crispy_forms_tags %}
{% block new %}
<section class="content">

  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Nouveau Membre</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="box-body">
        {{ form|crispy }}
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </div>
    </form>
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}

admini/templates/admini/newPurchase.html
{% extends "admini/adminBase.html" %}
{% load crispy_forms_tags %}
{% block new %}
<section class="content">

  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Nouvel Achat</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="box-body">
        {{ form|crispy }}
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </div>
    </form>
  </div><!-- /.box -->

</section><!-- /.content -->

{% endblock new %}